name: Valgrind

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y valgrind gcc make
      - name: Build
        run: ./_build.sh
      - name: Run Valgrind
        run: cd Build/GNU.MinGW && valgrind -s --leak-check=full --error-exitcode=1 ./bkasm ../../tests/test.asm
