namespace Bkasm
{
    public static class LexerTable
    {
        public static class Bk
        {
            public static readonly Lexema[] WordTable = new Lexema[]
            {
                new Lexema(eIdentKind.OP, eIdentType.TOK_CC, "CC", 0xDC, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CM, "CM", 0xFC, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CP, "CP", 0xF4, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CZ, "CZ", 0xCC, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DB, "DB", 0, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DI, "DI", 0xF3, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DS, "DS", 0, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DW, "DW", 0, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_EI, "EI", 0xFB, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_IN, "IN", 0xDB, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JC, "JC", 0xDA, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JM, "JM", 0xFA, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JP, "JP", 0xF2, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JZ, "JZ", 0xCA, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RC, "RC", 0xD8, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RM, "RM", 0xF8, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RP, "RP", 0xF0, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RZ, "RZ", 0xC8, 2),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ACI, "ACI", 0xCE, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ADC, "ADC", 0x88, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ADD, "ADD", 0x80, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ADI, "ADI", 0xC6, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ANA, "ANA", 0xA0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_AND, "AND", 0xA0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ANI, "ANI", 0xE6, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CMA, "CMA", 0x2F, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CMC, "CMC", 0x3F, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CMP, "CMP", 0xB8, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CNC, "CNC", 0xD4, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CNZ, "CNZ", 0xC4, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CPE, "CPE", 0xEC, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CPI, "CPI", 0xFE, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CPO, "CPO", 0xE4, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DAA, "DAA", 0x27, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DAD, "DAD", 0x09, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DCR, "DCR", 0x05, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_DCX, "DCX", 0x0B, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_EQU, "EQU", 0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_HLT, "HLT", 0x76, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_INR, "INR", 0x04, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_INX, "INX", 0x03, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JMP, "JMP", 0xC3, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JNC, "JNC", 0xD2, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JNZ, "JNZ", 0xC2, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JPE, "JPE", 0xEA, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_JPO, "JPO", 0xE2, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_LDA, "LDA", 0x3A, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_LXI, "LXI", 0x01, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_MOV, "MOV", 0x40, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_MVI, "MVI", 0x06, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_NOP, "NOP", 0x00, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ORA, "ORA", 0xB0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ORG, "ORG", 0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_ORI, "ORI", 0xF6, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_OUT, "OUT", 0xD3, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_POP, "POP", 0xC1, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RAL, "RAL", 0x17, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RAR, "RAR", 0x1F, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RET, "RET", 0xC9, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RIM, "RIM", 0x20, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RLC, "RLC", 0x07, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RNC, "RNC", 0xD0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RNZ, "RNZ", 0xC0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RPE, "RPE", 0xE8, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RPO, "RPO", 0xE0, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RRC, "RRC", 0x0F, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_RST, "RST", 0xC7, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_SBB, "SBB", 0x98, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_SBI, "SBI", 0xDE, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_SIM, "SIM", 0x30, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_STA, "STA", 0x32, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_STC, "STC", 0x37, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_SUB, "SUB", 0x90, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_SUI, "SUI", 0xD6, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_XRA, "XRA", 0xA8, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_XRI, "XRI", 0xEE, 3),
                new Lexema(eIdentKind.OP, eIdentType.TOK_CALL, "CALL", 0xCD, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_LDAX, "LDAX", 0x0A, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_LHLD, "LHLD", 0x2A, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_PCHL, "PCHL", 0xE9, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_PUSH, "PUSH", 0xC5, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_SHLD, "SHLD", 0x22, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_SPHL, "SPHL", 0xF9, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_STAX, "STAX", 0x02, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_XCHG, "XCHG", 0xEB, 4),
                new Lexema(eIdentKind.OP, eIdentType.TOK_XTHL, "XTHL", 0xE3, 4),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGA, "A", 0x7, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGB, "B", 0x0, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGC, "C", 0x1, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGD, "D", 0x2, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGE, "E", 0x3, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGH, "H", 0x4, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGL, "L", 0x5, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGM, "M", 0x6, 1),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGBC, "BC", 0x0, 2),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGDE, "DE", 0x2, 2),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGHL, "HL", 0x4, 2),
                new Lexema(eIdentKind.REG, eIdentType.TOK_REGSP, "SP", 0x6, 2),
                new Lexema(eIdentKind.REG, eIdentType.TOK_PSW, "PSW", 0x6, 3),
                new Lexema(eIdentKind.INT, eIdentType.TOK_END, "END", 0, 3),
                new Lexema(eIdentKind.INT, eIdentType.TOK_INCLUDE, "INCLUDE", 0, 7),
            };
            public static readonly Lexema[] SymbolTable = new Lexema[]
            {
                new Lexema(eIdentKind.SYM, eIdentType.TOK_COLON, ":", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_SEMICOLON, ";", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_COMMA, ",", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_EQ, "=", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_GT, ">", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_LT, "<", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_PLUS, "+", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_MINUS, "-", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_ASTERISK, "*", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_LPAREN, "(", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.TOK_RPAREN, ")", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.L_EOL, "\n", 0, 1),
                new Lexema(eIdentKind.SYM, eIdentType.L_EOF, "\xff", 0, 1),
            };
        }
    }
}
